### ISSUE TITLE
nltk missing

### ISSUE THREAD

**Issue by kafkaphoenix** [UtilityHotbar/rpgtools#4]
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
Traceback (most recent call last):
  File "c:\Users\sorak\Documents\GitHub\civsim\civsim\civsim.py", line 13, in <module>
    from third.rpgtools.lang_gen import make_language
  File "c:\Users\sorak\Documents\GitHub\civsim\civsim\third\rpgtools\lang_gen.py", line 7, in <module>
    from nltk.stem.porter import *
ModuleNotFoundError: No module named 'nltk'

It seems this module is also required so it should be added to civsim requirements

There is actually 2 fixes for this:
- adding a setup.py to civsim installing that requirement
- https://stackoverflow.com/questions/12332975/installing-python-module-within-code

**Comment by kafkaphoenix** [comment]
@UtilityHotbar This is still happening

**Comment by UtilityHotbar** [comment]
@kafkaphoenix I think I've removed the nltk code?

**Comment by kafkaphoenix** [comment]
okey thanks for the update
